apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexnum-secrets
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nexnum-secrets # The K8s secret to be created
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: secret/nexnum/prod
      property: database_url
  - secretKey: REDIS_URL
    remoteRef:
      key: secret/nexnum/prod
      property: redis_url
  - secretKey: JWT_SECRET
    remoteRef:
      key: secret/nexnum/prod
      property: jwt_secret
  - secretKey: CRON_SECRET
    remoteRef:
      key: secret/nexnum/prod
      property: cron_secret
