apiVersion: v1
kind: Secret
metadata:
  name: nexnum-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:pass@host:5432/db?schema=public"
  REDIS_URL: "redis://localhost:6379"
  JWT_SECRET: "your-secret-key"
  MEILISEARCH_HOST: "http://meilisearch:7700"
  MEILISEARCH_KEY: "masterKey"
  CRON_SECRET: "cron-secret-123"
